### ISSUE TITLE
Cannot set property 'isMobile' of undefined

### ISSUE THREAD

**Issue by BassemN** [kaimallea/isMobile#44]
Hi,

Thank you for this great library :).
After adding this library to my website, I got the below error 
`Uncaught TypeError: Cannot set property 'isMobile' of undefined`
please advise

Thanks

**Comment by kaimallea** [comment]
Is this still a problem? Can you provide some more context? Which browser(s) are you using and how are you adding the library to your site?

**Comment by kaimallea** [comment]
Feel free to re-open if this is still an issue!

**Comment by atef-ayed** [comment]
Error:


Traceback:
TypeError: Cannot read property 'isMobile' of undefined
    at QWeb.eval (eval at _compile (https://exemple.com/web/content/368-3f23171/web.assets_common.js:961:178), <anonymous>:20:53)
    at QWeb.fn (https://exemple.com//web/content/368-3f23171/web.assets_common.js:943:173)
    at QWeb.render (https://jexemple.com//web/content/368-3f23171/web.assets_common.js:950:20)
    at Object.__owl__.renderFn (https://exemple.com//web/content/5804-e420fb1/web.assets_backend.js:1332:147)
    at PatchableClass.__render (https://exemple.com//web/content/368-3f23171/web.assets_common.js:1266:33)
    at PatchableClass.__prepareAndRender (https://exemple.com//web/content/368-3f23171/web.assets_common.js:1264:29)
