### ISSUE TITLE
Serverside usage doesn't handle being passed undefined

### ISSUE THREAD

**Issue by CallumJFraser** [kaimallea/isMobile#68]
we had a use case (have now fixed our side) where if you call 

```
isMobile(undefined)
```

you get an error:

```
TypeError: Cannot read property 'use' of undefined
    at module.exports (/Users/aUser/Projects/sanitycheck/node_modules/isMobile/lib/isMobile.js:2:13)
    at Object.<anonymous> (/Users/aUser/Projects/sanitycheck/index.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by kaimallea** [comment]
Fixed by #77
